{% set name = "libsecret" %}
{% set version = "0.18.8" %}
{% set sha256 = "3bfa889d260e0dbabcf5b9967f2aae12edcd2ddc9adc365de7a5cc840c311d15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://ftp.gnome.org/pub/gnome/sources/libsecret/0.18/libsecret-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - 0001-Disable-tests-which-require-additional-deps.patch
    - 0002-Fix-hard-coded-shebang-in-tap-scripts.patch

build:
  number: 1
  skip: True  # [win]
  run_exports:
    #  https://abi-laboratory.pro/tracker/timeline/libsecret/
    - {{ pin_subpackage('libsecret', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - intltool
    - pkg-config
    - sed  # [osx]
    - perl
    - python 2.7
  host:
    - glib
    - libgcrypt


test:
  commands:
    - test -f $PREFIX/lib/libsecret-1$SHLIB_EXT
    - test -f $PREFIX/lib/pkgconfig/libsecret-1.pc
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://wiki.gnome.org/Projects/Libsecret
  license: LGPL-2.1
  license_family: LGPL
  license_file: COPYING
  summary: 'GObject based library for accessing the Secret Service API.'
  description: |
    libsecret is a library for storing and retrieving passwords and other
    secrets. It communicates with the "Secret Service" using D-Bus.
    gnome-keyring and ksecretservice are both implementations of a Secret
    Service. libsecret replaces libgnome-keyring.
  doc_url: https://developer.gnome.org/libsecret/
  dev_url: https://git.gnome.org/browse/libsecret/

extra:
  recipe-maintainers:
    - nehaljwani
