travis:
  secure:
    BINSTAR_TOKEN: iKutWGZQzINDZooLdIXwHXex77Zjyd54QbZzuLm0o8jfv5piyhV8uLutmx2Mz8jvNO0X0T7KtJbLDAwIJHovKjY4ZiKfjsfCVkEL3NlboQsmiLm3m2LvOTA4Ege2M/S2LrjtTepzxoLGimS14CWYBM5qOCyWB2YTrj4DG/1KZ2OrDEl3GhbHMcjb0b0XGmoIbRRAvVhOaCrqG4v5maOyok51nOqfIamjhmS6LkoaV8g123t0zJBzyvROYRRtK5OVpbne3QrRba2MmBK0OKdDkSM5xZce+HQQkhSzuGDsO7WsXpcCa+3W2lGNmTXPSmuy/4+xC9uiBZdrxjnOMq57NrOUu9NF0rSWXnPYVvDS8ZdSjbfApqxDcZHw0DvoKmHgg1NmnAxMpemAgWsrCvQsSTp4dkvW6MwpbJNh7c7/UB2wLgiA7ZJwrk78QUUxAb6x4n8Ai5r6CFvE+zVNURXbKdZW2jpQJf6vrwHUuW5bA0H/RBf93Yn10x1U8oxtgVvlIZ8Upmxyz5l3Czx8CTq0x73SK64UMRkhO86e9qJLQ6MUSLfMKwiodwH7OJl943yzOjPN45g7GsDYkg3uo20kAnJjVC8259k9A7LyjmBb3fiTNxbxsq/qwbIClGMPlBWbOUzk3vkWd0/4wMpITkUeqVspk0kFwYue5dSQazBdgvo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
