travis:
  secure:
    BINSTAR_TOKEN: nTM+PJgJB0zELjgadwSuQhD4jLE3nH1lAKA0n83qKQAb6YvsaLdRwr0KMbfuFvGXEO76wsATUuyUVO5+7msFc1nst7ZpRo4FfCErsOlD/xrlTDbp9KPDD1TTmE1ByGHU5H0aXEbl4Z+zAP42nfLa21Dv1IDzgHWrNgLu7KHHYfNPIISuJlCMWmiAI3cVeC78r5RDp3hSeY20NzeYiTXLqbo42ab3CmFtfXoBzn2seQGRK2j3T3fqt4l/ElLfsyXU8gdZVZ46F/JgMmnD/itPmmB1AZlW4J+aABJVu2khPPk00X3vBeCSeq6zC1f675J7aLLQFnQjpNER1RtASFdFvok4c07IZ2m2C5qjTnxszWeVLlYiyPR+/a75cGQUEfczGWfNrSfMl+uFCxkcZ7/Ed2sbJmFfwNTGhQXqPqYhfbqoyVpO2nQlP3l5GFAiuJdyXhP/S10WEIOYM+rgP1CYMBMb7+6rgfS59xjKXYfb4phraSqLDPShcxBP9ANbrhIRffL651I9tbkjaaqeDTOSJIwS1UmJm1cbUMDHdcqPLH88XI8jvAL6VygCBFg2/DDUbbVWhpWl+VpsUCJLmJX7jNIKiZzcqDyWDe1+S267ejuFZCCs5QpZTg5W5gpCLaxAqgOsdkq6AnWqG3VtHq+I7Q1RDQpIp6bOqMYGdHxmmZ4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
